apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  selector:
    matchLabels:
      app: template
  replicas: 1
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
      - name: ctn
        image: template-image
        imagePullPolicy: IfNotPresent