apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: template-namespace
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
        app: template
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
      - name: ctn
        image: template-image
        imagePullPolicy: Always
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        - name: https
          protocol: TCP
          containerPort: 443
        #resources:
          #requests:
            #cpu: "20m"
            #memory: "55Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          successThreshold: 1
          failureThreshold: 2
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          successThreshold: 1
          failureThreshold: 2
          periodSeconds: 10
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: configmap
        - secretRef:
            name: secret