apiVersion: apps/v1
kind: Deployment
metadata:
  name: SET_DEPLOY_NAME
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: SET_LABEL
  template:
    metadata:
      labels:
        app: SET_LABEL
    spec:
      containers:
      - name: -ctn
        image: SET_IMAGE
        imagePullPolicy: Always
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        - name: https
          protocol: TCP
          containerPort: 443
        env:
        - name: TZ
          value: "Asia/Tokyo"
        envFrom:
        - configMapRef:
            name: -configmap
        - secretRef:
            name: -secret
