apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: template-namespace
spec:
  selector:
    app: template
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 443
  type: NodePort